# Generated by Django 3.1.3 on 2021-06-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0005_auto_20210509_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='prefix',
            field=models.IntegerField(default=34),
        ),
    ]
