# Generated by Django 3.1.3 on 2021-06-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0028_auto_20210424_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bandera',
        ),
    ]
