# Generated by Django 3.1.3 on 2021-06-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0029_remove_product_bandera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='bandera',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fecha',
        ),
    ]
