# Generated by Django 3.1.3 on 2021-06-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0031_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.descuento'),
        ),
    ]
