# Generated by Django 3.1.3 on 2021-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210412_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cityDestination1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=20, null=True),
        ),
    ]
