# Generated by Django 3.1.3 on 2021-06-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0005_auto_20210509_1439'),
        ('members', '0006_auto_20210621_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descuentosApp.country'),
        ),
    ]
