# Generated by Django 3.1.3 on 2021-06-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20210621_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cityDestination1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=20),
        ),
    ]
